version: 0.0
os: linux
files:
  - source: /
    destination: /dist/main.js
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 3000
      runas: root
  AfterInstall:
    - location: scripts/install_nodejs
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

