version: '3.7'

services:
    postgres:
        image: postgres:latest
        ports: ['5454:5454']
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: db
    redis:
        image: redis:alpine
        command: redis-server --requirepass secret
        ports: ['6400:6379']
